name: ASPNETCoreCI

on:
  push:
    branches: [ main ]
jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: dotnet run --project ./build/_build.csproj
        run: |
          dotnet run  --project ./build/_build.csproj
        env:
          DockerRegistryPassword: ${{ secrets.DockerRegistryPassword }}